language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: kTV1oa5oc8GY2yXatLLGarEOlQMjgL5raXfmHAVwRyLQXSvEAOLqFFPw/2me79PSuYwKWYaEQ9TSPNIsk66lQQekQ0BY4mBssLGTGVPHXdNd2M0AwXVsZHXSST4v64sbjJO6GKSSWG0by45C1h99HzSpxTOJWm/zjaGjeznZXNvfXiqifyBm6ui/PJdNM7oscUqu1HpqSGvOHiC97xT5ExGWXZsmY7rBOES9BxIhfMnLYNr/vuSVBY2Czb97hP1cNaCAdtCSuVsIx6c2zqVnvhKtOYq/tOQ/Tbvj31Z28oEOumwDUoT3/afVQ5CdecrWAyTKbG7a1o7HFAzPKV9hkK7xNS2WaAbB1udHh4txtjv2hNKow5UNpZbPmNoLo21YLH0R9XGFtLNn0/cajAKQpzPhFQjUER9XBS7K3UwOCL2ch26QxHewZkB9BccI+SKjcnKqltO6Qw0K/sU00lP9px86qMi4L7G7Q+igYv3TpWPCOWkwQ7vtlia0BTdlh5Y736vXFmIhabGlG1qFDUV7Ppv219xf4RICCGIS9l+ON2kGjeS7OtN4vR03XGSxW8w7HyfQN6raK8Sq6CKnhLF2RfHfSLZrGBEgDNrYSuTAee3L2uzHDp96QyWjqCSNcGl8jkbA0GW0LKoJDkPoq1T83/SZ4hJHCGCkIvI7+oGRODA=
  app: palette-picker-mttwlkr

